ExecuteAutoEmployee/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ExecuteAutoEmployee.Models
{
    public class Employee
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public float Salary { get; set; }

        public int DurationWorked { get; set; }

        public int Grade { get; set; }

        public string Email { get; set; }

        public virtual ICollection<Benefits> Benefits { get; set; }

    }
}

ExecuteAutoEmployee/Controllers/BenefitController.cs
using ExecuteAutoEmployee.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExecuteAutoEmployee.Controllers
{
    public class BenefitController : Controller
    {

        //Get the database
        EmployeeDb _employeeDb = new EmployeeDb();

        // GET: Benefit
        public ActionResult Index()
        {
            return View();
        }

        // GET: Benefit/Details/5
        public ActionResult Details(int id)
        {
            var emp = _employeeDb.Employee.Find(id);
            return View(emp);
        }

        // GET: Benefit/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Benefit/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Benefit/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Benefit/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Benefit/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Benefit/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ExecuteAutoEmployee/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ExecuteAutoEmployee.Models;
using System.Data.Entity;

namespace ExecuteAutoEmployee.Controllers
{
    public class EmployeeController : Controller
    {
        //Get the database
        EmployeeDb _employeeDb = new EmployeeDb();

        // GET: Employee
        public ActionResult Index(string searchTerm = null)
        {
            var emp = _employeeDb.Employee.Where(x => searchTerm == null || x.Name.StartsWith(searchTerm));
            return View(emp);
        }

        // GET: Employee/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Employee/Create
        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public ActionResult Create(Employee employee)
        {
                if(ModelState.IsValid)
                {
                    _employeeDb.Employee.Add(employee);
                    _employeeDb.SaveChanges();
                    return RedirectToAction("Index", new { id = employee.Id });
                }

            return View(employee);
        }

        // GET: Employee/Edit/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int id)
        {
            var employee = _employeeDb.Employee.FirstOrDefault(x => x.Id == id);
            return View(employee);
        }

        // POST: Employee/Edit/5
        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(Employee employee)
        {
            if (TryUpdateModel(employee))
            {
                _employeeDb.Entry(employee).State = EntityState.Modified;
                _employeeDb.SaveChanges();
                return RedirectToAction("Index", new { id = employee.Id });
            }
            return View(employee);
        }

        // GET: Employee/Delete/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int id)
        {
            var employee = _employeeDb.Employee.FirstOrDefault(x => x.Id == id);
            return View(employee);
        }

        // POST: Employee/Delete/5
        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int id, Employee employee)
        {
            if (TryUpdateModel(employee))
            {
                _employeeDb.Entry(employee).State = EntityState.Deleted;
                _employeeDb.SaveChanges();
                return RedirectToAction("Index", new { id = employee.Id });
            }
            return View(employee);
        }
    }
}

ExecuteAutoEmployee/Views/Employee/Create.cshtml
@model ExecuteAutoEmployee.Models.Employee

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create new employee</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Employee</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Salary, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Salary, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Salary, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.DurationWorked, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DurationWorked, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DurationWorked, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Grade, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Grade, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Grade, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

ExecuteAutoEmployee/Views/Employee/Delete.cshtml
@model ExecuteAutoEmployee.Models.Employee

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete @Model.Name ?</h3>
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Salary)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Salary)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.DurationWorked)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.DurationWorked)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Grade)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Grade)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

ExecuteAutoEmployee/Views/Employee/Edit.cshtml
@model ExecuteAutoEmployee.Models.Employee

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Employee</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
    
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Salary, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Salary, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Salary, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.DurationWorked, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DurationWorked, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DurationWorked, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Grade, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Grade, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Grade, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

ExecuteAutoEmployee/Views/Employee/Index.cshtml
@model IEnumerable<ExecuteAutoEmployee.Models.Employee>

<form method="get" style="text-align:right" class="input-list style-1 clearfix">
    @if (Roles.IsUserInRole("Administrator"))
    {
        @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary", @style = "color:white, text-align:left" })
    }
    <input type="text" name="searchTerm" placeholder="Search Name" />
    <input type="submit" value="Search" class="btn btn-default" />
</form>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Salary)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DurationWorked)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Grade)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salary)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DurationWorked)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Grade)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.ActionLink("Benefits", "Details", "Benefit", new { id = item.Id }, null)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id })
            </td>
            <td>
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>