ExecuteAutoEmployee/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ExecuteAutoEmployee.Models;
using System.Data.Entity;

namespace ExecuteAutoEmployee.Controllers
{
    public class EmployeeController : Controller
    {
        //Get the database
        EmployeeDb _employeeDb = new EmployeeDb();

        // GET: Employee
        public ActionResult Index(string searchTerm = null)
        {
            var emp = _employeeDb.Employee.Where(x => searchTerm == null || x.Name.StartsWith(searchTerm));
            return View(emp);
        }

        // GET: Employee/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Employee/Create
        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public ActionResult Create(Employee employee)
        {
                if(ModelState.IsValid)
                {
                    _employeeDb.Employee.Add(employee);
                    _employeeDb.SaveChanges();
                    return RedirectToAction("Index", new { id = employee.Id });
                }

            return View(employee);
        }

        // GET: Employee/Edit/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int id)
        {
            var employee = _employeeDb.Employee.FirstOrDefault(x => x.Id == id);
            return View(employee);
        }

        // POST: Employee/Edit/5
        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(Employee employee)
        {
            if (TryUpdateModel(employee))
            {
                _employeeDb.Entry(employee).State = EntityState.Modified;
                _employeeDb.SaveChanges();
                return RedirectToAction("Index", new { id = employee.Id });
            }
            return View(employee);
        }

        // GET: Employee/Delete/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int id)
        {
            var employee = _employeeDb.Employee.FirstOrDefault(x => x.Id == id);
            return View(employee);
        }

        // POST: Employee/Delete/5
        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int id, Employee employee)
        {
            if (TryUpdateModel(employee))
            {
                _employeeDb.Entry(employee).State = EntityState.Deleted;
                _employeeDb.SaveChanges();
                return RedirectToAction("Index", new { id = employee.Id });
            }
            return View(employee);
        }
    }
}

ExecuteAutoEmployee/Controllers/EmployeeDetailsController.cs
using ExecuteAutoEmployee.Models;
using ExecuteAutoEmployee.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExecuteAutoEmployee.Controllers
{
    [Authorize(Roles = "Administrator,User")]
    public class EmployeeDetailsController : Controller
    {

        //Get the database
        EmployeeDb _employeeDb = new EmployeeDb();

        PFServiceClient.PFServiceClient pfCalc = new PFServiceClient.PFServiceClient();


        // GET: EmployeeDetails
        public ActionResult Index(string searchTerm = null)
        {
            var emp = _employeeDb.Employee.Where(x => searchTerm == null || x.Name.StartsWith(searchTerm));
            return View(emp);
        }

        public ActionResult EmployeePF(int id)
        {
            var employee = _employeeDb.Employee.Find(id);
            //Convert to Service Employee
            var emp = ConvertToServiceEmp(employee);

            var contrib = pfCalc.GetPfEmployeeContribSofar(emp);
            ViewBag.EmployeeContrib = contrib;

            return View(employee);
        }


        public ActionResult EmployeeBonus(int id)
        {
            var employee = _employeeDb.Employee.Where(x => x.Id == id).FirstOrDefault();

            //Convert to Service Employee
            var emp = ConvertToServiceEmp(employee);

            var contrib = pfCalc.GetPfEmployerContribSofar(emp);
            ViewBag.EmployerContrib = contrib;

            return View(employee);
        }

        public PFServiceClient.Employee ConvertToServiceEmp(Employee employee)
        {
            PFServiceClient.Employee emp = new PFServiceClient.Employee()
            {
                Name = employee.Name,
                Id = employee.Id,
                DurationWorked = employee.DurationWorked,
                Salary = employee.Salary
            };

            return emp;
        }


    }
}

ExecuteAutoEmployee/Controllers/RoleController.cs
using ExecuteAutoEmployee.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExecuteAutoEmployee.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class RoleController : Controller
    {

        //Get the database
        EmployeeDb _employeeDb = new EmployeeDb();

        // GET: Role
        public ActionResult Index()
        {
            //Do not display admin user inturn :)
            var Users = _employeeDb.Users.Where(x => x.UserName != "admin").ToList();

            //Get all the Roles
            var list = _employeeDb.Roles.OrderBy(role => role.Name).ToList().Select(role => new SelectListItem { Value = role.Name.ToString(), Text = role.Name }).ToList();
            ViewBag.Roles = list;

            return View(Users);
        }

        // GET: Role/Details/5
        public ActionResult AssignRole(string userName, string roleName)
        {
            ApplicationUser user = _employeeDb.Users.Where(usr => usr.UserName.Equals(userName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(_employeeDb));


            if (user != null)
            {
                userManager.AddToRoleAsync(user.Id, roleName);

                ViewBag.ResultMessage = "Role created successfully !";
            }
            else
            {
                ViewBag.ErrorMessage = "Sorry user is not available";
            }


            return RedirectToAction("Index");
        }

        // GET: Role/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Role/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Role/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Role/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Role/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Role/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ExecuteAutoEmployee/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Execute Automation Employee App</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Employee List", "Index", "Employee")</li>
                    @if (Roles.IsUserInRole("Administrator"))
                    {
                        <li>@Html.ActionLink("Employee Details", "Index", "EmployeeDetails")</li>
                        <li>@Html.ActionLink("Manage Users", "Index", "Role")</li>
                    }
                    @if (Roles.IsUserInRole("User"))
                    {
                        <li>@Html.ActionLink("Employee Details", "Index", "EmployeeDetails")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Powered by ExecuteAutomation.com</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>